# This is a basic workflow to help you get started with Actions...helelo

name: GCP-CLI 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  GCP_CLI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: set project one
        run: |
         gcloud config configurations list
         gcloud config set project macro-truck-322711
         
      - name : gsutil create new bucket
        run : gsutil mb gs://hello-new-demo-123456
        
      - name:  gstil command
        run : gsutil ls
      
         
